service: buergerbot

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.run_app
    packRequirements: false

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
